<script setup lang="ts">
import { ref, onMounted } from 'vue'; import { useRoute } from 'vue-router'; import { getPublicNote, listComments, addComment, reactNote } from '@/api/user'; import { ElMessage } from 'element-plus'
const route=useRoute();const note=ref<any>(null);const comments=ref<any[]>([]);const comment=ref('');const id=Number(route.params.id)
onMounted(async()=>{note.value=(await getPublicNote(id)).data;comments.value=(await listComments(id)).data||[]})
async function send(){if(!comment.value.trim())return;await addComment(id,comment.value);comments.value=(await listComments(id)).data||[];comment.value=''}
async function react(type:'like'|'favorite'){await reactNote(id,type);ElMessage.success(type==='like'?'已点赞':'已收藏')}
</script>
<template><main v-if="note" class="detail-page"><p class="eyebrow">TRAVEL NOTE</p><h1>{{note.title}}</h1><p class="author">{{note.user_id}} · {{note.created_at}}</p><img v-if="note.cover_url" class="cover" :src="note.cover_url"/><article class="content">{{note.content}}</article><div class="actions"><button @click="react('like')">♡ {{note.like_count}}</button><button @click="react('favorite')">☆ 收藏</button></div><section class="comments"><h2>评论 {{note.comment_count}}</h2><div v-for="c in comments" :key="c.id" class="comment"><b>{{c.user_id}}</b><p>{{c.content}}</p></div><div class="comment-box"><input v-model="comment" placeholder="分享你的想法" @keyup.enter="send"/><button @click="send">发送</button></div></section></main></template>
<style scoped>.detail-page{width:min(760px,calc(100% - 40px));margin:auto;padding:42px 0 80px}.eyebrow{color:var(--sunset);font-size:10px;font-weight:800;letter-spacing:.16em}h1{font:38px 'DM Serif Display';margin:8px 0}.author{color:var(--ink-3);font-size:12px}.cover{width:100%;max-height:420px;object-fit:cover;border-radius:18px;margin:22px 0}.content{white-space:pre-wrap;line-height:1.9;font-size:15px}.actions{display:flex;gap:10px;margin:24px 0}.actions button,.comment-box button{border:1px solid var(--line);background:var(--card);padding:10px 15px;border-radius:9px;cursor:pointer}.comments{border-top:1px solid var(--line);padding-top:20px}.comments h2{font-size:19px}.comment{padding:12px 0;border-bottom:1px solid var(--line)}.comment b{font-size:12px;color:var(--forest)}.comment p{margin:5px 0 0}.comment-box{display:flex;gap:8px;margin-top:16px}.comment-box input{flex:1;border:1px solid var(--line);border-radius:9px;padding:10px;background:var(--card)}</style>
