<script setup lang="ts">
import { ref, onMounted } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { getPublicNote, listComments, addComment, reactNote } from '@/api/user'; import { ElMessage } from 'element-plus'
const route=useRoute();const router=useRouter();const note=ref<any>(null);const comments=ref<any[]>([]);const comment=ref('');const id=Number(route.params.id);const loading=ref(true);const error=ref(false);const sending=ref(false)
async function load(){loading.value=true;error.value=false;try{note.value=(await getPublicNote(id)).data;comments.value=(await listComments(id)).data||[]}catch{error.value=true}finally{loading.value=false}}
onMounted(load)
async function send(){if(!comment.value.trim()||sending.value)return;sending.value=true;try{await addComment(id,comment.value);comments.value=(await listComments(id)).data||[];comment.value='';ElMessage.success('评论已发送')}catch{ElMessage.error('评论发送失败')}finally{sending.value=false}}
async function react(type:'like'|'favorite'){try{await reactNote(id,type);ElMessage.success(type==='like'?'已点赞':'已收藏')}catch{ElMessage.error('操作失败，请稍后重试')}}
function imageUrl(value?: string){const raw=String(value||'').trim();if(!raw)return '';if(/^(https?:|data:|blob:)/i.test(raw))return raw;const base=String(import.meta.env.VITE_API_BASE_URL||'').replace(/\/$/,'');return `${base}${raw.startsWith('/')?raw:`/${raw}`}`}
function openUser(userId?: string){if(userId)router.push(`/users/${encodeURIComponent(userId)}`)}
</script>
<template><main v-loading="loading" class="detail-page"><template v-if="error"><p class="empty">笔记加载失败，请刷新重试。</p></template><template v-else-if="note"><p class="eyebrow">TRAVEL NOTE</p><h1>{{note.title}}</h1><button class="author author-button" @click="openUser(note.user_id)"><span class="avatar"><img v-if="imageUrl(note.author_avatar || note.authorAvatar)" :src="imageUrl(note.author_avatar || note.authorAvatar)" alt=""/><span v-else>{{(note.author || note.user_id || '旅').charAt(0)}}</span></span>{{note.author || note.author_name || note.user_id}} · {{note.created_at}}</button><img v-if="note.cover_url" class="cover" :src="imageUrl(note.cover_url)"/><article class="content">{{note.content}}</article><div class="actions"><button @click="react('like')">♡ {{note.like_count}}</button><button @click="react('favorite')">☆ 收藏</button></div><section class="comments"><h2>评论 {{note.comment_count}}</h2><div v-for="c in comments" :key="c.id" class="comment"><button class="comment-author" @click="openUser(c.user_id)"><span class="avatar small"><img v-if="imageUrl(c.avatar)" :src="imageUrl(c.avatar)" alt=""/><span v-else>{{(c.nickname || c.user_id || '旅').charAt(0)}}</span></span>{{c.nickname || c.user_id || '旅行者'}}</button><p>{{c.content}}</p></div><div class="comment-box"><input v-model="comment" placeholder="分享你的想法" @keyup.enter="send"/><button :disabled="sending" @click="send">{{sending?'发送中…':'发送'}}</button></div></section></template></main></template>
<style scoped>.detail-page{width:min(760px,calc(100% - 40px));margin:auto;padding:42px 0 80px}.eyebrow{color:var(--sunset);font-size:10px;font-weight:800;letter-spacing:.16em}h1{font:38px 'DM Serif Display';margin:8px 0}.author{color:var(--ink-3);font-size:12px}.author-button,.comment-author{display:inline-flex;align-items:center;gap:7px;border:0;background:transparent;padding:0;cursor:pointer}.author-button:hover,.comment-author:hover{color:var(--forest);text-decoration:underline}.avatar{width:24px;height:24px;display:grid;place-items:center;overflow:hidden;border-radius:50%;background:var(--roam-soft);color:var(--forest);font-size:10px;font-weight:800}.avatar.small{width:21px;height:21px}.avatar img{width:100%;height:100%;object-fit:cover}.cover{width:100%;max-height:420px;object-fit:cover;border-radius:18px;margin:22px 0}.content{white-space:pre-wrap;line-height:1.9;font-size:15px}.actions{display:flex;gap:10px;margin:24px 0}.actions button,.comment-box button{border:1px solid var(--line);background:var(--card);padding:10px 15px;border-radius:9px;cursor:pointer}.comments{border-top:1px solid var(--line);padding-top:20px}.comments h2{font-size:19px}.comment{padding:12px 0;border-bottom:1px solid var(--line)}.comment-author{color:var(--forest);font-size:12px;font-weight:700}.comment p{margin:5px 0 0}.comment-box{display:flex;gap:8px;margin-top:16px}.comment-box input{flex:1;border:1px solid var(--line);border-radius:9px;padding:10px;background:var(--card)}</style>
